version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
    steps:
        - add_ssh_keys:
          fingerprints:
            - "ca:2d:3a:b2:78:8b:14:0c:20:61:ad:fc:e8:71:4e:43"

        - run:
            name: install dependencies
            command: |
               python3 -m venv venv
               . venv/bin/activate
               pip install -r requirements.txt

        - run:
            name: run tests
            command: |
              . venv/bin/activate
              python .circleci/run_tests.py

